# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9328796b3b9bb818c79e7100332a4c1992c91aca30a0570a6ef4f50824d1893003fb2d1d0c3214565cd2000d820405a870396c0fc7eda8def71937461dbb7ad1

test:
  secret_key_base: f5b203c67f59df592a268fe1b44a0ceb4df5ac1cf686f40f92bc22c85ece8029e0654440977bc02afad640de219e10430b61a280f468d5d0fe19b564b93ae89a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
